# -*- coding: utf-8 -*-
"""장표별 이름 · slide_page · 검색 키워드 정의(장표 내 문구 기반)."""

# 전체 패키지 공통 태그(모든 낱장에도 얹는다 — 이 제안서를 통으로 찾을 때)
COMMON_KO = ["기후위기", "기후위기적응", "적응정보", "통합플랫폼", "국립환경과학원",
             "제안서", "발표장표", "공공사업", "솔리데오", "2026"]
COMMON_EN = ["climate crisis", "climate adaptation", "adaptation information",
             "integrated platform", "proposal", "presentation deck", "public project"]

PKG = {
    "name": "국가 기후위기 적응정보 통합플랫폼 구축·운영(2026) 제안 설명회",
    "ko": ["기후위기적응", "적응정보", "통합플랫폼", "국가플랫폼", "제안설명회", "제안발표",
           "발표장표", "제안서", "국립환경과학원", "기후에너지환경부", "공공사업", "구축운영",
           "KADT", "표준DB", "데이터연계", "웹지아이에스", "지아이에스", "공간정보", "정책지원",
           "적응대책", "기후리스크", "영향체인", "지자체", "중앙부처", "솔리데오", "컨소시엄",
           "사업제안", "수행계획", "48장", "풀패키지"],
    "en": ["climate adaptation", "adaptation information", "integrated platform",
           "national platform", "proposal presentation", "rfp response", "public sector",
           "KADT", "standard database", "data integration", "web gis", "spatial data",
           "policy support", "climate risk", "impact chain", "local government",
           "government ministry", "consortium", "project plan", "full deck"],
}

# (번호, slide_page, 이름, 한글 키워드, 영문 키워드)
SLIDES = [
 (1, "cover", "제안 설명회 표지 — 국가 기후위기 적응정보 통합플랫폼(2026)",
  ["표지", "제안표지", "설명회표지", "기후위기", "적응정보", "통합플랫폼", "지구", "손", "푸른지구", "타이틀", "제목장표", "발표시작", "국립환경과학원", "제안설명회", "2026"],
  ["cover", "title slide", "proposal cover", "climate", "earth in hands", "opening", "presentation title"]),
 (2, "content", "제안사 소개 — 전국민이 사용하는 행정정보서비스 실적",
  ["제안사소개", "회사소개", "구축실적", "행정정보서비스", "정부24", "보조금24", "식품안전나라", "새올행정", "공공마이데이터", "레퍼런스", "수행실적", "신뢰성", "국가표준시스템", "포트폴리오"],
  ["company introduction", "track record", "reference", "government services", "portfolio", "credentials"]),
 (3, "toc", "목차 — 사업의 이해·추진 전략·사업관리·맺음말",
  ["목차", "차례", "아젠다", "발표순서", "컨텐츠", "구성", "인덱스", "4단계", "심플목차"],
  ["table of contents", "agenda", "outline", "index", "contents"]),
 (4, "divider", "간지 PART 1 — 사업의 이해",
  ["간지", "파트간지", "챕터", "구분장표", "사업의이해", "PART1", "섹션표지", "심플간지"],
  ["divider", "section break", "chapter", "part 1", "understanding"]),
 (5, "content", "추진배경 — 같은 폭염, 다른 피해(부문별 기후 피해 사례)",
  ["추진배경", "폭염", "온열질환", "가뭄", "녹조", "양식폐사", "농작물피해", "기후피해", "재난", "부문별피해", "사례", "통계", "심각성", "문제제기", "보건", "농축식품", "해양수산", "물환경"],
  ["background", "heat wave", "heat illness", "drought", "algae bloom", "crop damage", "climate damage", "case study", "sector impact"]),
 (6, "content", "기후위기 적응의 법적 기반 — 관계부처·지자체 적응대책 체계",
  ["법적기반", "근거법령", "탄소중립기본법", "적응대책", "관계부처", "지자체", "공공기관", "국가리스크", "추진체계", "거버넌스", "기본계획", "제도"],
  ["legal basis", "carbon neutrality act", "adaptation measures", "ministries", "governance", "framework", "national risk"]),
 (7, "content", "문제 정의 — 기관별 정보 분산·기준 불일치·판단의 어려움",
  ["문제정의", "정보분산", "기준불일치", "판단어려움", "사일로", "데이터파편화", "이용불편", "현황문제", "페인포인트", "기상청", "질병관리청", "농식품부"],
  ["problem statement", "data silo", "fragmentation", "inconsistent standard", "pain point", "as-is issue"]),
 (8, "content", "사업의 목표 및 방향 — 쉽고 편하게, 빠르고 바르게",
  ["사업목표", "추진방향", "비전", "통합관리", "사용자", "자치단체", "중앙부처", "연구계", "산업계", "일반국민", "학계", "목표선언", "지향점"],
  ["objective", "direction", "vision", "target users", "integrated management", "goal"]),
 (9, "content", "추진 로드맵 — 2025~2029 단계별 구축 계획",
  ["로드맵", "추진일정", "단계별계획", "연차별", "마일스톤", "타임라인", "1단계", "2단계", "3단계", "정식오픈", "중장기계획", "간트"],
  ["roadmap", "timeline", "milestone", "phased plan", "schedule", "multi year"]),
 (10, "content", "범위 및 내용 — 3대 관점 과업 체계화(서비스·데이터·인프라)",
  ["사업범위", "과업내용", "요구사항", "3대관점", "서비스관점", "데이터관점", "인프라관점", "73개요구사항", "과업체계", "범위정의", "WBS"],
  ["scope", "requirements", "work breakdown", "service", "data", "infrastructure", "task definition"]),
 (11, "divider", "간지 PART 2 — 사업 추진 전략",
  ["간지", "파트간지", "챕터", "구분장표", "사업추진전략", "PART2", "섹션표지"],
  ["divider", "section break", "chapter", "part 2", "strategy"]),
 (12, "content", "사업 특성 1/4 — 통합과 맞춤(적응정보의 정의와 활용 주체)",
  ["사업특성", "통합", "맞춤형", "적응정보정의", "활용주체", "연계수집", "제공활용", "의사결정지원", "이해관계자", "개념도", "구조도"],
  ["characteristics", "integration", "customization", "definition", "stakeholder", "concept diagram"]),
 (13, "content", "사업 특성 2/4 — 표준·품질·연계 체계 필요성",
  ["표준화", "데이터품질", "연계체계", "품질관리", "표준준수", "공유활용", "KADT", "메타데이터", "정합성", "신뢰성", "비교표", "AsIs ToBe"],
  ["standardization", "data quality", "integration", "metadata", "consistency", "as-is to-be"]),
 (14, "content", "사업 특성 3/4 — 국가 기후리스크 중심 분석·시각화",
  ["분석시각화", "시각화", "대시보드", "기후리스크", "웹지아이에스", "지도", "차트", "활용시나리오", "화면예시", "UI", "리스크분석", "통계자료"],
  ["visualization", "dashboard", "climate risk", "web gis", "map", "chart", "scenario", "ui mockup"]),
 (15, "content", "사업 특성 4/4 — R&D 연구사업과의 유기적 협력",
  ["연구협력", "R&D", "연구사업", "유기적협력", "연구성과", "영향체인연구", "표준DB", "API구축", "협업체계", "선순환", "UNIST"],
  ["r&d collaboration", "research", "impact chain", "standard db", "api", "cooperation"]),
 (16, "content", "이슈 1/2 — 착수 시점 연계 대상 미확정 리스크",
  ["이슈", "리스크", "연계대상", "미확정", "불확실성", "중점리스크", "농축식품", "보건", "물환경", "해양수산", "신규부문", "고도화부문", "대응필요"],
  ["issue", "risk", "uncertainty", "undefined scope", "key risk", "sector"]),
 (17, "content", "이슈 2/2 — 착수 3개월 내 성과 가시화 요구",
  ["이슈", "성과가시화", "착수3개월", "연말성과보고", "일정압박", "조기성과", "인력구성", "개발환경", "시행착오", "사업성공", "타임라인"],
  ["issue", "quick win", "early result", "three months", "performance report", "schedule pressure"]),
 (18, "content", "추진 전략 총괄 — 3대 전략과 공통 실행기반",
  ["추진전략", "전략총괄", "전략체계", "3대전략", "공통기반", "전략수립", "이슈대응", "한장정리", "전략맵", "요약"],
  ["strategy overview", "strategy map", "three strategies", "common base", "summary"]),
 (19, "divider", "전략 1 표지 — 선제적 데이터 연계·표준화",
  ["전략간지", "전략1", "선제적연계", "데이터표준화", "액션정리", "섹션표지", "구분장표"],
  ["strategy divider", "strategy 1", "data integration", "standardization", "action list"]),
 (20, "content", "전략1 Action1 — 연계 후보 데이터 선제 확보",
  ["데이터연계", "후보데이터", "선제확보", "수집방법", "OpenAPI", "크롤링", "파일수신", "연계목록", "데이터수집", "물환경", "해양수산", "엑셀목록"],
  ["data collection", "candidate data", "open api", "crawling", "file transfer", "integration list"]),
 (21, "content", "전략1 Action2 — 영향체인 기반 후보 데이터 선정",
  ["영향체인", "데이터선정", "기후영향인자", "노출과정", "핵심리스크", "영향피해", "체계적선정", "농업용수", "체인다이어그램", "기준정립"],
  ["impact chain", "data selection", "climate driver", "exposure", "core risk", "damage", "systematic"]),
 (22, "divider", "전략 2 표지 — 경험 기반 신속 실현·조기 검증",
  ["전략간지", "전략2", "신속실현", "조기검증", "액션정리", "섹션표지", "구분장표"],
  ["strategy divider", "strategy 2", "rapid delivery", "early validation"]),
 (23, "content", "전략2 Action1 — 1차 자산 기반 고도화 착수(두 단계 앞선 출발)",
  ["기존자산활용", "고도화착수", "선행사업", "차별화", "출발점", "단계비교", "STEP", "조기착수", "경쟁우위", "시연"],
  ["existing assets", "head start", "advancement", "differentiation", "step comparison"]),
 (24, "content", "전략2 Action2 — 신규 부문 화면 조기 검증(프로토타입)",
  ["프로토타입", "조기검증", "화면검증", "신규부문", "샘플데이터", "지도", "차트", "지표", "사전검증", "시각화확인", "성과보고활용"],
  ["prototype", "early validation", "screen mockup", "sample data", "map", "chart", "indicator"]),
 (25, "content", "전략2 Action3 — 하이브리드 개발방법론(S-SEM) 적용",
  ["개발방법론", "하이브리드", "폭포수", "애자일", "SSEM", "품질통제", "반복검증", "단계별산출물", "안정성", "완성도", "프로세스"],
  ["methodology", "hybrid", "waterfall", "agile", "quality control", "iteration", "deliverable"]),
 (26, "divider", "전략 3 표지 — 사용자 중심 서비스 고도화",
  ["전략간지", "전략3", "사용자중심", "서비스고도화", "액션정리", "섹션표지", "구분장표"],
  ["strategy divider", "strategy 3", "user centric", "service enhancement"]),
 (27, "content", "전략3 Action1 — 역할별 맞춤 서비스(정책담당자·연구자·국민)",
  ["역할별서비스", "맞춤형", "퍼소나", "정책담당자", "연구자", "일반국민", "권한", "차별화", "사용자시나리오", "지역리스크순위", "보고서저장"],
  ["role based", "persona", "policy maker", "researcher", "citizen", "permission", "customized service"]),
 (28, "content", "전략3 Action2 — 공간 기반 정책서비스 고도화(현재-미래 비교)",
  ["공간분석", "웹지아이에스", "지도비교", "현재미래", "시나리오비교", "중첩분석", "취약지역", "정책판단", "드래그비교", "위험지역", "공간통계"],
  ["spatial analysis", "web gis", "map comparison", "scenario", "overlay", "vulnerable area", "policy decision"]),
 (29, "content", "전략3 Action3 — 영향체인 기반 판단정보 통합(근거 추적)",
  ["판단정보", "근거추적", "출처표기", "영향체인", "데이터추적", "드릴다운", "신뢰성", "리스크흐름", "상세조회", "투명성"],
  ["traceability", "evidence", "source", "impact chain", "drill down", "transparency"]),
 (30, "content", "전략3 Action4 — 외부 평가결과 연계·관리(VESTAP 등)",
  ["평가결과연계", "취약성평가", "VESTAP", "MOTIVE", "평가도구", "비교분석", "산출근거", "적응대책지원", "외부연계", "평가관리"],
  ["assessment integration", "vulnerability", "evaluation tool", "comparison", "adaptation support"]),
 (31, "divider", "전략 4 표지 — 공통 실행기반(안정·품질)",
  ["전략간지", "전략4", "공통실행기반", "안정성", "품질", "액션정리", "섹션표지", "구분장표"],
  ["strategy divider", "strategy 4", "common foundation", "stability", "quality"]),
 (32, "content", "전략4 Action1 — 전자정부 표준프레임워크 기반 MSA",
  ["전자정부표준프레임워크", "MSA", "마이크로서비스", "아키텍처", "S-Platform", "구조도", "확장성", "모듈", "API게이트웨이", "기술구조", "시스템구성도"],
  ["egov framework", "msa", "microservice", "architecture", "scalability", "api gateway", "system diagram"]),
 (33, "content", "전략4 Action2 — Web-GIS 표출성능 최적화",
  ["성능최적화", "웹지아이에스", "표출성능", "렌더링", "공간조회", "타일", "응답속도", "튜닝", "캐시", "성능측정", "개선근거"],
  ["performance", "web gis", "rendering", "spatial query", "tile", "response time", "tuning", "cache"]),
 (34, "content", "전략4 Action3 — 전 주기 데이터 품질 보장(자동검증)",
  ["데이터품질", "자동검증", "품질기준", "임계판정", "조치이력", "정합성", "수집데이터", "품질지표", "KADT표준DB", "상시관리", "품질관리체계"],
  ["data quality", "automated validation", "threshold", "audit trail", "quality metric", "standard db"]),
 (35, "content", "전략4 Action4 — AI 학습 데이터셋 구성(예측모델 PoC)",
  ["인공지능", "AI학습데이터", "데이터셋", "예측모델", "PoC", "시범구축", "물공급부족", "전망", "머신러닝", "학습DB", "AI활용"],
  ["artificial intelligence", "training dataset", "prediction model", "poc", "machine learning", "forecast"]),
 (36, "content", "전략4 Action5 — G-클라우드 이관 및 안정화 (1/2)",
  ["클라우드이관", "지클라우드", "국가정보자원관리원", "이관요건", "보안요건", "장애대응", "이중화", "백업", "복구", "안정화", "운영실적"],
  ["cloud migration", "g-cloud", "security requirement", "redundancy", "backup", "recovery", "stabilization"]),
 (37, "content", "전략4 Action5 — G-클라우드 HW/SW 구성도 (2/2)",
  ["구성도", "HW구성", "SW구성", "분리발주", "네트워크구성", "웹서버", "WAS", "DB", "NoSQL", "스토리지", "시스템구성도", "인프라설계", "상세설계"],
  ["configuration diagram", "hardware", "software", "network", "web server", "was", "database", "storage", "infrastructure"]),
 (38, "divider", "간지 PART 3 — 사업관리 및 지원",
  ["간지", "파트간지", "챕터", "구분장표", "사업관리", "PART3", "섹션표지"],
  ["divider", "section break", "chapter", "part 3", "project management"]),
 (39, "content", "수행 조직의 구성 1/2 — 컨소시엄 상호 협력체계",
  ["수행조직", "컨소시엄", "협력체계", "참여기업", "참여비율", "역할분담", "전문기업", "상생협력", "조직도", "파트너"],
  ["organization", "consortium", "partnership", "role", "participation", "partner company"]),
 (40, "content", "수행 조직의 구성 2/2 — 선행사업 인력 투입(PM·핵심인력)",
  ["인력구성", "투입인력", "PM", "사업총괄", "수석", "경력", "연속성", "핵심인력", "프로필", "선행사업", "안정성보장"],
  ["staffing", "project manager", "key personnel", "experience", "continuity", "profile"]),
 (41, "content", "프로젝트 관리 1/2 — SP 2등급 방법론 9대 관리영역",
  ["프로젝트관리", "SP인증", "SP2등급", "관리영역", "9대영역", "일정관리", "위험관리", "품질관리", "형상관리", "이슈관리", "범위관리", "방법론"],
  ["project management", "sp certification", "management area", "schedule", "risk", "quality", "configuration"]),
 (42, "content", "프로젝트 관리 2/2 — 사업 일정 통제(월별 마스터 스케줄)",
  ["사업일정", "마스터스케줄", "월별계획", "간트차트", "진행단계", "착수", "중간보고", "완료보고", "감리", "일정통제", "협업일정", "WBS"],
  ["master schedule", "gantt chart", "monthly plan", "kickoff", "interim report", "audit", "schedule control"]),
 (43, "content", "프로젝트 지원 1/2 — 3개월 차 성과보고 지원 방안",
  ["프로젝트지원", "성과보고", "3개월", "조기검증", "착수보고회", "중간보고회", "완료보고회", "지원방안", "성공전략", "노하우"],
  ["project support", "performance report", "kickoff meeting", "interim", "completion", "support plan"]),
 (44, "content", "프로젝트 지원 2/2 — 5대 지원활동(교육·기술·하자보수·안정화)",
  ["지원활동", "5대지원", "교육훈련", "기술지원", "하자보수", "안정화", "형상관리", "자원관리", "문서관리", "보안관리", "진도관리", "유지보수"],
  ["support activity", "training", "technical support", "warranty", "stabilization", "maintenance"]),
 (45, "divider", "간지 맺음말 — 최고의 선택, 솔리데오 컨소시엄",
  ["간지", "맺음말", "결론간지", "구분장표", "최고의선택", "섹션표지", "클로징"],
  ["divider", "closing", "conclusion", "best choice", "section break"]),
 (46, "content", "맺음말 — 왜 솔리데오인가(구축·유지보수 히스토리)",
  ["맺음말", "결론", "차별성", "구축이력", "연혁", "히스토리", "레퍼런스", "신뢰", "역량", "설득", "타임라인", "국가시스템"],
  ["conclusion", "why us", "history", "timeline", "reference", "capability", "credibility"]),
 (47, "etc", "감사합니다 — 약속은 지키고 책임은 다 하겠습니다",
  ["감사합니다", "마무리", "클로징", "엔딩", "약속", "책임", "메시지", "감사인사", "마지막장표"],
  ["thank you", "closing", "ending", "commitment", "final slide"]),
 (48, "qa", "질의응답",
  ["질의응답", "QA", "질문", "답변", "큐앤에이", "마무리", "토론", "질의"],
  ["q&a", "question", "answer", "discussion"]),
]
